apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: basic-template
objects:
# DEPLOYMENT
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/part-of: ${APP_GROUP}
      app.openshift.io/runtime: ${APP_RUNTIME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP_NAME}
    strategy:
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - name: application
          image: image-registry.openshift-image-registry.svc:5000/${APP_NAMESPACE}/${APP_NAME}:latest       
          ports:
          - containerPort: 8080
            protocol: TCP
            name: 8080-tcp
# SERVICE
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
# ROUTE
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
parameters:
  - name: APP_NAME
  - name: APP_RUNTIME
  - name: APP_GROUP
  - name: APP_NAMESPACE

